version: "3"

services:
  nginx:
    image: nginx:1.13.8-alpine
    ports:
      - 10000:80
      - 20000:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/web
